spring.application.name=transaction-service
spring.docker.compose.enabled=true
server.servlet.context-path=/transaction-service
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/transaction_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081